### ISSUE TITLE
Zahlungen - Transaktions-Datenbank

### ISSUE THREAD

**Issue by BlackReacon** [DavidSchuchert/VereinsManagementTool#3]
Die Datenbank sollte sortierbar sein nach Jahr, Einnahmen/Ausgaben, PayPal/Bank.

**Comment by BlackReacon** [comment]
Wenn man eine neue Transaktion hinzufügt, sollte man schon direkt beim erstellen den FilePath nutzen können.

**Comment by BlackReacon** [comment]
Je mehr Transaktionen hinzugefügt werden, desto weiter muss man nach unten scrollen, um eine neue Transaktion zu adden. Ggf. Button "Neue Transaktion" sowie das Bearbeitungsfeld nach oben setzten

**Comment by DavidSchuchert** [comment]
wird in der nächsten Version alle drin sein.
